/* =====================================================================
   WHO SEES WHAT ON HELP, COMPUTED RATHER THAN DESCRIBED.

   Matt (dh): "give me a table of which guides, leaflets and FAQs each
   level sees on the Help page (admin, opndoor manager, agency
   Director, Manager, Negotiator, supplier Management, Referrer,
   Developer), and confirm for each that nothing shows rates,
   commission or anything that level shouldn't see".

   =====================================================================
   WHY THIS IS A TEST AND NOT A DOCUMENT I WROTE
   =====================================================================

   A hand-written table is a claim about the code. This one is
   GENERATED by running the real gates -- `mayOpenResource` and
   `mayOpenFaq`, the same two functions the page calls -- over the real
   catalogue, for each of Matt's eight readers. It is written to
   docs/HELP-MATRIX.md on every run, so the document cannot drift from
   the product: change a gate and the table changes with it.

   AND THE SAFETY CHECKS ARE ASSERTIONS, not a sentence in the table
   saying I checked. A Manager who can be shown a commission guide
   fails the suite.

   =====================================================================
   WHAT THIS DOES NOT COVER, AND IT IS THE LARGER HALF
   =====================================================================

   (dk) asks for the table to be level BY CHECKING SETTING -- straight
   to payment, Opndoor's decision first, or the tenant's eligibility
   check with the GBP 20 fee -- because the journey a guide describes
   has to be the journey that organisation actually gets.

   NOTHING IN THE CATALOGUE CARRIES A SETTING. A resource has `rail`,
   `minRole` and `needsCommission` and no `mode`, so there is one set
   of documents for all three journeys and the table below has one
   column where Matt asked for three. That is a content build, not a
   gate, and it is recorded as not done rather than approximated here:
   a table with three identical columns would read as an answer.
   ===================================================================== */
import { describe, expect, it } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { HELP_SEED } from '@/data/mock/help';
import { mayOpenResource, mayOpenFaq, type HelpViewer } from './Help';

/** Matt's eight, in his order. */
const READERS: { label: string; v: HelpViewer }[] = [
  { label: 'opndoor admin', v: { role: 'superadmin', seesCommission: true, agency: false, admin: true } },
  { label: 'opndoor manager', v: { role: 'opndoor_manager', seesCommission: false, agency: false, admin: true } },
  { label: 'agency Director', v: { role: 'management', seesCommission: true, agency: true, admin: false } },
  { label: 'agency Manager', v: { role: 'management', seesCommission: false, agency: true, admin: false } },
  { label: 'agency Negotiator', v: { role: 'referrer', seesCommission: false, agency: true, admin: false } },
  { label: 'supplier Management', v: { role: 'management', seesCommission: true, agency: false, admin: false } },
  { label: 'supplier Referrer', v: { role: 'referrer', seesCommission: false, agency: false, admin: false } },
  { label: 'supplier Developer', v: { role: 'developer', seesCommission: false, agency: false, admin: false } },
];

type Res = Parameters<typeof mayOpenResource>[0];
/* THE TWO SECTIONS BY NAME, from HelpContent. My first version read
   `HELP_SEED.resources`, which does not exist -- the shape is
   `gettingStarted` and `templates` as siblings of `faqs`. It produced
   a table reading "0 resources" for all eight readers, which is the
   kind of empty answer a generated document makes look authoritative. */
const allResources = (): { section: string; r: Res }[] => [
  ...HELP_SEED.gettingStarted.map((r) => ({ section: 'Getting started', r: r as Res })),
  ...HELP_SEED.templates.map((r) => ({ section: 'Templates', r: r as Res })),
];

const seenBy = (v: HelpViewer) => ({
  resources: allResources().filter(({ r }) => mayOpenResource(r, v)),
  faqs: (HELP_SEED.faqs ?? []).filter((f) => mayOpenFaq(f, v)),
});

describe('the Help matrix', () => {
  it('is written to docs/HELP-MATRIX.md from the real gates', () => {
    const lines: string[] = [
      '# Who sees what on Help',
      '',
      '> GENERATED by `src/pages/Help/theHelpMatrix.test.ts`. Do not edit by hand:',
      '> it is produced by running the page’s own `mayOpenResource` and',
      '> `mayOpenFaq` over the real catalogue, so it cannot drift from the product.',
      '',
      '## The gap Matt asked about',
      '',
      '(dk) asks for this table by LEVEL **and by checking setting** — straight to',
      'payment, Opndoor’s decision first, or the tenant’s eligibility check with the',
      '£20 fee. Nothing in the catalogue carries a setting: a resource has `rail`,',
      '`minRole` and `needsCommission` and no `mode`. So there is one set of',
      'documents for all three journeys, and this table has one column where three',
      'were asked for. That is a content build, not a gate, and it is **not done**.',
      '',
      '## Counts',
      '',
      '| Reader | Guides, leaflets and templates | FAQs |',
      '| --- | ---: | ---: |',
    ];
    for (const { label, v } of READERS) {
      const s = seenBy(v);
      lines.push(`| ${label} | ${s.resources.length} | ${s.faqs.length} |`);
    }
    for (const { label, v } of READERS) {
      const s = seenBy(v);
      lines.push('', `## ${label}`, '');
      lines.push('**Resources**', '');
      for (const { section, r } of s.resources) {
        lines.push(`- ${r.title} _(${section}${r.needsCommission ? ', commission' : ''}${r.rail ? `, ${r.rail} rail` : ''})_`);
      }
      if (!s.resources.length) lines.push('- _none_');
      lines.push('', '**FAQs**', '');
      for (const f of s.faqs) lines.push(`- ${f.q}`);
      if (!s.faqs.length) lines.push('- _none_');
    }
    mkdirSync(join(process.cwd(), 'docs'), { recursive: true });
    writeFileSync(join(process.cwd(), 'docs/HELP-MATRIX.md'), `${lines.join('\n')}\n`, 'utf8');
    expect(lines.length).toBeGreaterThan(20);
    /* AND IT IS NOT AN EMPTY TABLE. A generated document saying every
       reader sees nothing looks authoritative and is the likeliest way
       this file lies: one wrong property name and it reports zero for
       all eight. */
    expect(allResources().length).toBeGreaterThan(5);
    for (const { label, v } of READERS) {
      expect(seenBy(v).resources.length, `${label} sees no resources at all`).toBeGreaterThan(0);
    }
  });
});

describe('and nothing reaches a reader who should not have it', () => {
  /* THE ONE MATT NAMES FIRST: "no commission content for Managers,
     Negotiators, Referrers or Developers". A Manager exists precisely
     so somebody can run the team without being shown what the agency
     earns, and a guide describing commission hands it to them in
     prose. */
  const noMoney = READERS.filter((r) => !r.v.admin && !r.v.seesCommission);

  it.each(noMoney.map((r) => [r.label, r.v] as const))(
    '%s is shown no commission resource', (_label, v) => {
      expect(seenBy(v).resources.filter((x) => x.r.needsCommission)).toEqual([]);
    });

  it.each(noMoney.map((r) => [r.label, r.v] as const))(
    '%s is shown no commission FAQ', (_label, v) => {
      expect(seenBy(v).faqs.filter((f) => f.needsCommission)).toEqual([]);
    });

  /* THE RAIL. Supplier material describes referring somebody else's
     stock, adding agencies on the fly, white-labelling and the sales
     conversation. Shown to one of our own agencies it describes a
     product they are not using. */
  it.each(READERS.filter((r) => r.v.agency).map((r) => [r.label, r.v] as const))(
    '%s is shown no supplier-rail material', (_label, v) => {
      expect(seenBy(v).resources.filter((x) => x.r.rail === 'supplier')).toEqual([]);
      expect(seenBy(v).faqs.filter((f) => f.rail === 'supplier')).toEqual([]);
    });

  /* AND THE ADMIN GUIDE IS ADMIN-ONLY. It describes reconciliation,
     rate management and the bordereau: opndoor's own machinery. */
  it.each(READERS.filter((r) => r.v.role !== 'superadmin').map((r) => [r.label, r.v] as const))(
    '%s is not shown the opndoor admin guide', (_label, v) => {
      expect(seenBy(v).resources.some((x) => x.r.minRole === 'superadmin')).toBe(false);
    });

  /* NOBODY IS SHOWN NOTHING. A reader with an empty shelf is a
     mis-gate, not a policy -- every level has something to read. */
  it.each(READERS.map((r) => [r.label, r.v] as const))(
    '%s has something to read', (_label, v) => {
      const s = seenBy(v);
      expect(s.resources.length + s.faqs.length).toBeGreaterThan(0);
    });
});
