/* =====================================================================
   WHO SEES WHAT ON HELP, COMPUTED RATHER THAN DESCRIBED.

   Matt (dh): "give me a table of which guides, leaflets and FAQs each
   level sees on the Help page (admin, opndoor manager, agency
   Director, Manager, Negotiator, supplier Management, Referrer,
   Developer), and confirm for each that nothing shows rates,
   commission or anything that level shouldn't see".

   =====================================================================
   WHY THIS IS A TEST AND NOT A DOCUMENT I WROTE
   =====================================================================

   A hand-written table is a claim about the code. This one is
   GENERATED by running the real gates -- `mayOpenResource` and
   `mayOpenFaq`, the same two functions the page calls -- over the real
   catalogue, for each of Matt's eight readers. It is written to
   docs/HELP-MATRIX.md on every run, so the document cannot drift from
   the product: change a gate and the table changes with it.

   AND THE SAFETY CHECKS ARE ASSERTIONS, not a sentence in the table
   saying I checked. A Manager who can be shown a commission guide
   fails the suite.

   =====================================================================
   WHAT THIS DOES NOT COVER, AND IT IS THE LARGER HALF
   =====================================================================

   (dk) asks for the table to be level BY CHECKING SETTING -- straight
   to payment, Opndoor's decision first, or the tenant's eligibility
   check with the GBP 20 fee -- because the journey a guide describes
   has to be the journey that organisation actually gets.

   NOTHING IN THE CATALOGUE CARRIES A SETTING. A resource has `rail`,
   `minRole` and `needsCommission` and no `mode`, so there is one set
   of documents for all three journeys and the table below has one
   column where Matt asked for three. That is a content build, not a
   gate, and it is recorded as not done rather than approximated here:
   a table with three identical columns would read as an answer.
   ===================================================================== */
import { describe, expect, it } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { HELP_SEED } from '@/data/mock/help';
import { mayOpenResource, mayOpenFaq, type HelpViewer } from './Help';
import type { ReferencingMode } from '@/data';

/* (do) THE THIRD AXIS. Matt: "I asked for it to vary by checking
   setting too (accepts as sent, applies its own criteria, opndoor
   checks) ... so I can see e.g. that an 'accepts as sent' agency never
   sees eligibility checks or the GBP 20 fee." */
const MODES: { id: ReferencingMode; label: string }[] = [
  { id: 'pre_referenced_open', label: 'accepts as sent' },
  { id: 'pre_referenced_screened', label: 'applies its own criteria' },
  { id: 'opndoor_referenced', label: 'opndoor checks' },
];

/** Matt's eight, in his order. */
const READERS: { label: string; v: HelpViewer }[] = [
  { label: 'opndoor admin', v: { role: 'superadmin', seesCommission: true, agency: false, admin: true } },
  { label: 'opndoor manager', v: { role: 'opndoor_manager', seesCommission: false, agency: false, admin: true } },
  { label: 'agency Director', v: { role: 'management', seesCommission: true, agency: true, admin: false } },
  { label: 'agency Manager', v: { role: 'management', seesCommission: false, agency: true, admin: false } },
  { label: 'agency Negotiator', v: { role: 'referrer', seesCommission: false, agency: true, admin: false } },
  { label: 'supplier Management', v: { role: 'management', seesCommission: true, agency: false, admin: false } },
  { label: 'supplier Referrer', v: { role: 'referrer', seesCommission: false, agency: false, admin: false } },
  { label: 'supplier Developer', v: { role: 'developer', seesCommission: false, agency: false, admin: false } },
];

type Res = Parameters<typeof mayOpenResource>[0];
/* THE TWO SECTIONS BY NAME, from HelpContent. My first version read
   `HELP_SEED.resources`, which does not exist -- the shape is
   `gettingStarted` and `templates` as siblings of `faqs`. It produced
   a table reading "0 resources" for all eight readers, which is the
   kind of empty answer a generated document makes look authoritative. */
const allResources = (): { section: string; r: Res }[] => [
  ...HELP_SEED.gettingStarted.map((r) => ({ section: 'Getting started', r: r as Res })),
  ...HELP_SEED.templates.map((r) => ({ section: 'Templates', r: r as Res })),
];

const seenBy = (v: HelpViewer) => ({
  resources: allResources().filter(({ r }) => mayOpenResource(r, v)),
  faqs: (HELP_SEED.faqs ?? []).filter((f) => mayOpenFaq(f, v)),
});
const seenIn = (v: HelpViewer, mode: ReferencingMode) => seenBy({ ...v, mode });

describe('the Help matrix', () => {
  it('is written to docs/HELP-MATRIX.md from the real gates', () => {
    const lines: string[] = [
      '# Who sees what on Help',
      '',
      '> GENERATED by `src/pages/Help/theHelpMatrix.test.ts`. Do not edit by hand:',
      '> it is produced by running the page’s own `mayOpenResource` and',
      '> `mayOpenFaq` over the real catalogue, so it cannot drift from the product.',
      '',
      '## The gap Matt asked about',
      '',
      '(dk) asks for this table by LEVEL **and by checking setting** — straight to',
      'payment, Opndoor’s decision first, or the tenant’s eligibility check with the',
      '£20 fee. Nothing in the catalogue carries a setting: a resource has `rail`,',
      '`minRole` and `needsCommission` and no `mode`. So there is one set of',
      'documents for all three journeys, and this table has one column where three',
      'were asked for. That is a content build, not a gate, and it is **not done**.',
      '',
      '## Counts, by level and by checking setting',
      '',
      '`docs / FAQs` in each cell.',
      '',
      `| Reader | ${MODES.map((m) => m.label).join(' | ')} |`,
      '| --- | ---: | ---: | ---: |',
    ];
    for (const { label, v } of READERS) {
      const cells = MODES.map((m) => {
        const s = seenIn(v, m.id);
        return `${s.resources.length} / ${s.faqs.length}`;
      });
      lines.push(`| ${label} | ${cells.join(' | ')} |`);
    }
    for (const { label, v } of READERS) {
      lines.push('', `## ${label}`, '');
      for (const m of MODES) {
        const s = seenIn(v, m.id);
        lines.push(`### ${m.label}`, '', '**Resources**', '');
        for (const { section, r } of s.resources) {
          lines.push(`- ${r.title} _(${section}${r.needsCommission ? ', commission' : ''}${r.rail ? `, ${r.rail} rail` : ''})_`);
        }
        if (!s.resources.length) lines.push('- _none_');
        lines.push('', '**FAQs**', '');
        for (const f of s.faqs) lines.push(`- ${f.q}`);
        if (!s.faqs.length) lines.push('- _none_');
        lines.push('');
      }
    }
    mkdirSync(join(process.cwd(), 'docs'), { recursive: true });
    writeFileSync(join(process.cwd(), 'docs/HELP-MATRIX.md'), `${lines.join('\n')}\n`, 'utf8');
    expect(lines.length).toBeGreaterThan(20);
    /* AND IT IS NOT AN EMPTY TABLE. A generated document saying every
       reader sees nothing looks authoritative and is the likeliest way
       this file lies: one wrong property name and it reports zero for
       all eight. */
    expect(allResources().length).toBeGreaterThan(5);
    for (const { label, v } of READERS) {
      expect(seenBy(v).resources.length, `${label} sees no resources at all`).toBeGreaterThan(0);
    }
  });
});

describe('and nothing reaches a reader who should not have it', () => {
  /* THE ONE MATT NAMES FIRST: "no commission content for Managers,
     Negotiators, Referrers or Developers". A Manager exists precisely
     so somebody can run the team without being shown what the agency
     earns, and a guide describing commission hands it to them in
     prose. */
  const noMoney = READERS.filter((r) => !r.v.admin && !r.v.seesCommission);

  it.each(noMoney.map((r) => [r.label, r.v] as const))(
    '%s is shown no commission resource', (_label, v) => {
      expect(seenBy(v).resources.filter((x) => x.r.needsCommission)).toEqual([]);
    });

  it.each(noMoney.map((r) => [r.label, r.v] as const))(
    '%s is shown no commission FAQ', (_label, v) => {
      expect(seenBy(v).faqs.filter((f) => f.needsCommission)).toEqual([]);
    });

  /* THE RAIL. Supplier material describes referring somebody else's
     stock, adding agencies on the fly, white-labelling and the sales
     conversation. Shown to one of our own agencies it describes a
     product they are not using. */
  it.each(READERS.filter((r) => r.v.agency).map((r) => [r.label, r.v] as const))(
    '%s is shown no supplier-rail material', (_label, v) => {
      expect(seenBy(v).resources.filter((x) => x.r.rail === 'supplier')).toEqual([]);
      expect(seenBy(v).faqs.filter((f) => f.rail === 'supplier')).toEqual([]);
    });

  /* AND THE ADMIN GUIDE IS ADMIN-ONLY. It describes reconciliation,
     rate management and the bordereau: opndoor's own machinery. */
  it.each(READERS.filter((r) => r.v.role !== 'superadmin').map((r) => [r.label, r.v] as const))(
    '%s is not shown the opndoor admin guide', (_label, v) => {
      expect(seenBy(v).resources.some((x) => x.r.minRole === 'superadmin')).toBe(false);
    });

  /* (do) MATT'S OWN ACCEPTANCE TEST, in his words: "so I can see e.g.
     that an 'accepts as sent' agency never sees eligibility checks or
     the GBP 20 fee."

     ASSERTED OVER THE ANSWER TEXT, not over the tags. Tagging an item
     to a journey is the mechanism; what matters is that no WORD about
     an eligibility check or an application fee reaches a reader whose
     organisation has neither. A tag applied to the wrong item would
     pass a tag-shaped assertion and fail this one. */
  const ELIGIBILITY = /eligibility check|application fee|\u00a320|GBP 20/i;

  it.each(READERS.map((r) => [r.label, r.v] as const))(
    '%s on "accepts as sent" is told nothing about an eligibility check or a fee for one',
    (_label, v) => {
      const s = seenIn(v, 'pre_referenced_open');
      const offenders = s.faqs.filter((f) => ELIGIBILITY.test(`${f.q} ${f.a}`)).map((f) => f.q);
      expect(offenders).toEqual([]);
      expect(s.resources.filter((x) => ELIGIBILITY.test(`${x.r.title} ${x.r.desc}`))).toEqual([]);
    });

  /* AND THE MIRROR, WHICH IS TODAY'S REAL FAILURE AND IS RECORDED AS
     ONE RATHER THAN ASSERTED AWAY. Where opndoor checks the tenant,
     there IS a GBP 20 application fee and the catalogue says nothing
     about it anywhere -- so this test cannot demand the sentence
     exists without failing on content nobody has written. It pins the
     absence instead, so the day somebody writes it they are told to
     come back and turn this into the positive assertion. */
  it('while "opndoor checks" has no answer about the GBP 20 fee yet, which is the gap', () => {
    const all = [...(HELP_SEED.faqs ?? [])].map((f) => `${f.q} ${f.a}`).join(' ');
    expect(ELIGIBILITY.test(all), 'somebody has written the fee copy: make this a positive assertion')
      .toBe(false);
  });

  /* (dr4) ONLY A SUPPLIER ADDS AN AGENCY WHILE REFERRING, and nothing
     an agency reader sees may say otherwise. The guide's own text was
     already conditioned ("If you work at a supplier, you can...") and
     the three FAQs are rail-gated; it was the shelf DESCRIPTION,
     which is what they read before opening anything. */
  const ADDS_ORGS = /add (?:agencies|an agency|a new agency).{0,40}(?:on the fly|while)/i;

  it.each(READERS.filter((r) => r.v.agency).map((r) => [r.label, r.v] as const))(
    '%s is never told they can add an agency while referring', (_label, v) => {
      const s = seenBy(v);
      expect(s.resources.filter((x) => ADDS_ORGS.test(x.r.desc)).map((x) => x.r.title)).toEqual([]);
      expect(s.faqs.filter((f) => ADDS_ORGS.test(f.a)).map((f) => f.q)).toEqual([]);
    });

  /* AND A SUPPLIER STILL IS, because the capability is real and
     removing the claim from everybody would have hidden it from the
     readers who have it. */
  it('while a supplier Referrer still is', () => {
    const v = READERS.find((r) => r.label === 'supplier Referrer')!.v;
    const s = seenBy(v);
    const says = [...s.resources.map((x) => x.r.desc), ...s.faqs.map((f) => f.a)];
    expect(says.some((t) => /adding an agency or office while you refer|add a new one on the fly/i.test(t))).toBe(true);
  });

  /* NOBODY IS SHOWN NOTHING. A reader with an empty shelf is a
     mis-gate, not a policy -- every level has something to read. */
  it.each(READERS.map((r) => [r.label, r.v] as const))(
    '%s has something to read', (_label, v) => {
      const s = seenBy(v);
      expect(s.resources.length + s.faqs.length).toBeGreaterThan(0);
    });
});
