/* =====================================================================
   The API documentation panel, rendered from PARTNER-DOCS.md.

   Named ApiDocsPanel, not ApiDocs, because macOS and Windows filesystems are
   case-insensitive: ApiDocs.tsx and apiDocs.ts are the SAME FILE there, and
   TypeScript rejects the pair outright. Worth knowing before naming a component
   after its data module.
   Extraction and sanitising live in apiDocs.ts; this is only presentation.
   ===================================================================== */
import { Button } from '@/components/ui/Button';
import { Card, CardBody, CardHead } from '@/components/ui/Card';
import { CheckingJourney } from './CheckingJourney';
import type { ReferencingMode } from '@/data';
import { Icon } from '@/components/ui/Icon';
import { parseBlocks, partnerDocSections, specAvailable, type Block } from './apiDocs';

function Inline({ text }: { text: string }) {
  // Inline code and bold, the only inline markup the spec uses in these sections.
  const parts = text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g).filter(Boolean);
  return (
    <>
      {parts.map((p, i) => {
        if (p.startsWith('`') && p.endsWith('`')) return <code key={i}>{p.slice(1, -1)}</code>;
        if (p.startsWith('**') && p.endsWith('**')) return <strong key={i}>{p.slice(2, -2)}</strong>;
        return <span key={i}>{p}</span>;
      })}
    </>
  );
}

function Blocks({ blocks }: { blocks: Block[] }) {
  return (
    <>
      {blocks.map((b, i) => {
        if (b.kind === 'code') return <pre key={i} className="devcode"><code>{b.text}</code></pre>;
        if (b.kind === 'h') return <h4 key={i} className="devdoc__h">{b.text}</h4>;
        if (b.kind === 'ul') return <ul key={i} className="devdoc__ul">{b.items.map((it, j) => <li key={j}><Inline text={it} /></li>)}</ul>;
        if (b.kind === 'table') return (
          <div key={i} className="devdoc__tablewrap">
            <table className="dt">
              <thead><tr>{b.head.map((h, j) => <th key={j}><Inline text={h} /></th>)}</tr></thead>
              <tbody>{b.rows.map((r, j) => <tr key={j}>{r.map((c, k) => <td key={k}><Inline text={c} /></td>)}</tr>)}</tbody>
            </table>
          </div>
        );
        return <p key={i}><Inline text={b.text} /></p>;
      })}
    </>
  );
}

/* (dj) THE SAME PROPS AS GettingStarted, so the reference tab and the
   sequence tab agree about whose journey they describe. The panel
   renders the journey above the generated reference: the reference is
   the same for everybody, and which EVENTS and STATUSES a reader will
   actually see is not. */
export function ApiDocsPanel({ mode, orgName }: { mode?: ReferencingMode | null; orgName?: string | null } = {}) {
  const sections = specAvailable ? partnerDocSections() : [];

  if (!sections.length) {
    return (
      <>
      <CheckingJourney mode={mode ?? null} orgName={orgName ?? null} />
      <Card>
        <CardHead title="API documentation" sub="Generated from the specification" />
        <CardBody>
        <p className="soft">
          The documentation could not be generated from the specification. That means the section headings
          it looks for have been renamed, so the extraction list needs updating rather than the docs
          being rewritten here.
        </p>
        </CardBody>
      </Card>
      </>
    );
  }

  return (
    <>
    <CheckingJourney mode={mode ?? null} orgName={orgName ?? null} />
    <Card>
      <CardHead
        title="API documentation"
        sub="Generated from one source, so the prose and the OpenAPI description cannot drift"
        actions={
          <div className="devrowacts">
            {/* Served from /openapi.json, generated by the same script that
                renders everything below. Two links rather than one: a developer
                importing into Postman wants a URL to paste, and one saving it
                into their repo wants a file. Same document either way. */}
            <Button variant="ghost" size="sm" href="/openapi.json" target="_blank">
              <Icon name="external" /> View OpenAPI
            </Button>
            <Button variant="primary" size="sm" href="/openapi.json" download="opndoor-partner-api.openapi.json">
              <Icon name="download" /> Download spec
            </Button>
          </div>
        }
      />
      <CardBody>
        <div className="devopenapi">
          <Icon name="file" />
          <div>
            <strong>OpenAPI 3.1</strong>
            <p>
              Import <code>/openapi.json</code> into Postman, Insomnia or your client generator. It
              describes every endpoint, the request and response shapes, the error codes, the auth scheme
              and all six webhook event payloads. It is generated from the same source as this page on
              every build, so it cannot fall behind what is written here.
            </p>
          </div>
        </div>
      <div className="devdoc">
        {sections.map((s) => (
          <section key={s.id} className="devdoc__section">
            <h3 className="devdoc__title">{s.title}</h3>
            <Blocks blocks={parseBlocks(s.body)} />
          </section>
        ))}
      </div>
      </CardBody>
    </Card>
    </>
  );
}
