/* GENERATED FILE. Do not edit.
   Source: PARTNER-API.md
   Regenerate: node scripts/generate-partner-docs.mjs

   Only the partner-facing sections are extracted, and repo paths, defect
   references and open questions are stripped. The full specification is NOT
   bundled: importing it raw would ship the whole internal document to every
   browser, where filtering at render time does not help. */
export interface DocSection { id: string; title: string; body: string }

export const PARTNER_DOCS: DocSection[] = [
  {
    "id": "the-partner-facing-status-vocabulary",
    "title": "The partner-facing status vocabulary",
    "body": "Stored statuses are internal. Two read badly outside, so the API maps them, and\nthe same mapping is used by REST responses and webhook payloads alike.\n\n| Stored | Partner-facing | Why |\n| ------ | -------------- | --- |\n| `sent` | `sent` | |\n| `paid` | `paid` | |\n| `deed` | `deed_issued` | `deed` names a column, not an outcome |\n| `withdrawn` | `withdrawn` | |\n| `expired` | `lapsed` | `expired` collides with the guarantee's own expiry |\n\nThat last one matters. `status = 'expired'` means an **unpaid application lapsed\nafter 14 days**. `expiry_date` is the **guarantee expiring 12 months after\ntenancy start**. They are months apart and mean opposite things commercially, so\nthe partner-facing word for the first is `lapsed` and `expiry_date` keeps its\nname.\n\nThe `?status=` filter takes the partner vocabulary too, so a caller filters with\nthe same words the responses use."
  },
  {
    "id": "the-real-url-and-how-it-is-versioned",
    "title": "The real URL, and how it is versioned",
    "body": "**As built, the base is `/functions/v1/partner-api/v1/`**, so the live path is\n`/functions/v1/partner-api/v1/orgs`.\n\n**There are two different `v1`s in that path and they are unrelated.** The first\nis Supabase's Edge Function API version and is not ours to change. The second is\nthis API's version.\n\n**The version segment is required, not defaulted.** A request without it, or with\nan unrecognised one, gets:\n\n```\nHTTP 404\n{\"error\":{\"code\":\"unsupported_version\",\n          \"message\":\"Prefix the path with an API version. Supported: v1.\"}}\n```\n\nTreating a missing segment as `v1` would be friendlier today and useless later:\nthe clients that never sent a version are exactly the ones a v2 would break,\nwhich is the problem the segment exists to solve. It was added before any partner\nintegrated, so there was no compatibility to preserve and every client is\nexplicit from its first call.\n\nAdding v2 means adding it to `SUPPORTED_VERSIONS` and branching per endpoint.\nA custom domain rewriting to the function is the tidier long-term form and can\narrive later without changing the contract, because the version segment is\nalready there.\n\n**Idempotency keys are deliberately not version-qualified.** The ledger records\n`POST /applications`, not `POST /v1/applications`, so the same key sent to v1 and\nthen to v2 with the same body replays rather than creating a second application.\nVersion-qualifying it would turn a version migration into a duplicate-application\nrisk.\n\n---"
  },
  {
    "id": "reading-applications",
    "title": "Reading applications",
    "body": "`GET /applications` is keyset paginated on `(created_at, id)`, newest first.\n`?limit=` is clamped to 100 and `?status=` takes the partner vocabulary. The\nresponse carries `next_cursor`, which is **null on the last page**: a client\nloops until it is null rather than counting pages.\n\nKeyset rather than offset deliberately. Offset silently skips rows when new\napplications are created during a walk, which for a partner reconciling their\nbook means quietly missing records.\n\n**`payment_url` is returned by the single fetch and not by the list.** The\npayment token is a bearer credential for the tenant payment page, including the\nself-decline action, so returning a page of them to satisfy a reconciliation\nwalk is more exposure than the job needs. A partner acting on one application\nfetches it individually."
  },
  {
    "id": "4-2-key-format-and-hashing",
    "title": "Key format and hashing",
    "body": "```\nopnd_live_<32 random base62 chars>\n```\n\nThe prefix is the first **18** characters, `opnd_live_` plus 8 random, stored in\nclear as the lookup handle. It is not a secret. `opnd_test_` distinguishes\nnon-production keys.\n\n**The partner slug is deliberately not in the key.** An earlier draft included\nit. Two reasons it came out: the prefix has to be unique, and slug-derived\nprefixes collide between any two partners whose slugs share a first letter; and\na key fragment appearing in a log or a screenshot would otherwise name the\npartner.\n\n**Hashing is SHA-256, not Argon2id or scrypt.** Also a change from an earlier\ndraft, and worth the explanation because it looks wrong at a glance.\n\nThe key is 32 random base62 characters from a CSPRNG, roughly 190 bits. It is\nnot a user-chosen password, so there is no dictionary, no reuse across sites and\nnothing to brute force. A deliberately slow KDF exists to make guessing\nexpensive, and there is nothing here to guess.\n\nAgainst that it would cost two real things. It runs on **every** request,\nincluding unauthenticated ones, so a slow hash turns the auth path into a CPU\nexhaustion vector: an attacker sends garbage keys and each one costs the server\nfar more than it costs them. And it would make the identical-cost miss path in\n4.3 expensive to honour, because the miss path has to do the same work as the\nhit path by construction.\n\nThis is the same reasoning Stripe and GitHub apply to API keys. It would be the\nwrong choice for anything a human chooses."
  },
  {
    "id": "4-4-identical-failures",
    "title": "Identical failures",
    "body": "Every authentication failure, whatever the cause, returns byte-identical output:\n\n```\nHTTP 401\n{\"error\":{\"code\":\"unauthorized\",\"message\":\"Invalid credentials.\"}}\n```\n\nMalformed key, unknown prefix, wrong secret, revoked, expired: all the same. No\n`WWW-Authenticate` detail, no distinct codes, no hints. The response must not\nvary in body, status or headers.\n\nOnly the internal request log records the real reason. Partners debugging a\ngenuine problem get told out of band, which is a support cost accepted\ndeliberately in exchange for an unprobeable surface."
  },
  {
    "id": "4-5-scopes",
    "title": "Scopes",
    "body": "| Scope | Grants |\n| ----- | ------ |\n| `applications:write` | POST an application |\n| `applications:read` | Read own applications |\n| `orgs:read` | List agencies and branches |\n| `orgs:write` | Create agencies and branches implicitly on POST |\n| `webhooks:manage` | Register and modify own endpoints |\n\nA key without `orgs:write` that sends names instead of IDs is rejected rather\nthan quietly creating an org. This lets Opndoor issue a key that can only\nreference existing orgs, which is the sane end state for a mature partner."
  },
  {
    "id": "6-1-payload",
    "title": "Payload",
    "body": "Mirrors the New Application form. Field names are the API's own, in snake_case,\nmapped to columns internally.\n\n```jsonc\n{\n  \"idempotency_key\": \"partner-side-unique-string\",   // see section 11\n\n  \"tenant\": {\n    \"title\":      \"Mr\",           // required, one of Mr Mrs Miss Ms Mx Dr\n    \"first_name\": \"...\",          // required\n    \"last_name\":  \"...\",          // required\n    \"date_of_birth\": \"1990-04-12\",// required, ISO 8601, must be in the past\n    \"email\":      \"...\",          // required\n    \"phone\":      \"...\"           // required, must contain a digit\n  },\n\n  \"property\": {\n    \"address_line_1\": \"...\",      // required\n    \"address_line_2\": \"...\",      // optional\n    \"city\":           \"...\",      // required\n    \"county\":         \"...\",      // optional\n    \"postcode\":       \"SW1A 1AA\"  // required, UK format\n  },\n\n  \"tenancy\": {\n    \"monthly_rent\":  1250.00,     // required, > 0\n    \"start_date\":    \"2026-09-01\" // required\n  },\n\n  \"org\": {                        // exactly one of the two forms, section 7\n    \"agency_id\": \"uuid\",\n    \"branch_id\": \"uuid\"\n  },\n\n  \"referrer\": {\n    \"email\": \"agent@example.com\"  // required, section 8\n  }\n}\n```"
  },
  {
    "id": "9-4-the-field-codes-as-built",
    "title": "The field codes, as built",
    "body": "`public.referral_field_errors` is the single source of truth. `create_referral`\nand the API are both built on it, so the portal and the API cannot start\ndisagreeing about what a valid application is.\n\n| `field` | `code` |\n| ------- | ------ |\n| `tenant.title` | `invalid_value` |\n| `tenant.first_name`, `tenant.last_name` | `required` |\n| `tenant.date_of_birth` | `required`, `must_be_in_past`, `must_be_18_by_tenancy_start`, `implausible_age` |\n| `tenant.email` | `invalid_format` |\n| `tenant.phone` | `invalid_format` |\n| `property.address_line_1`, `property.city` | `required` |\n| `property.postcode` | `invalid_format` |\n| `tenancy.monthly_rent` | `must_be_positive` |\n| `tenancy.start_date` | `required`, `too_far_in_past`, `too_far_ahead` |\n| `org.agency_id`, `org.branch_id` | `required`, `not_found`, `no_agent_contact` |\n| `org.agency_name` | `insufficient_scope`, `could_not_create` |\n| `org.agent_contact_email` | `required` |\n| `referrer.email` | `required`, `not_available`, `could_not_provision` |\n\nTwo of these are worth understanding rather than just handling.\n\n**`org.branch_id: no_agent_contact`** means the branch cannot resolve a primary\nagent contact, so a deed could not be issued for it. Rejecting at POST is the\nwhole point: the alternative is accepting the application, taking the tenant's\nmoney, and failing at deed generation. `GET /orgs` exposes the same condition as\n`has_agent_contact` so a partner can fix their data before sending traffic.\n\n**`referrer.email: not_available`** means the address exists under a different\npartner. The message deliberately does not say which, or confirm that one exists.\n\nPostgres error text is never passed through. `create_referral`'s free-text\nmessages stay on the portal path.\n\n---"
  },
  {
    "id": "13-4-signing",
    "title": "Signing",
    "body": "Per-endpoint secret, HMAC-SHA256:\n\n```\nX-Opndoor-Signature: t=<unix>,v1=<hex hmac of \"<t>.<raw body>\">\nX-Opndoor-Event-Id: <uuid>\nX-Opndoor-Event-Type: application.paid\n```\n\nSigning the timestamp with the body, rather than the body alone, is what makes\nreplay detectable. Partners should reject a timestamp outside a tolerance of\naround five minutes.\n\nThe existing PandaDoc inbound verification is the closest precedent\n(_shared/pandadoc.ts:392) but it\ncompares with `===` and has **no timestamp, nonce or tolerance**, so it is\nreplayable. Do not copy it. Use the timing-safe helper from section 4.3, and\ndocument the tolerance so partners implement verification correctly."
  },
  {
    "id": "13-5-events",
    "title": "Events",
    "body": "| Event | Fires when | Backed by a real status today |\n| ----- | ---------- | ----------------------------- |\n| `application.created` | Created and accepted | `sent` |\n| `application.paid` | Payment settles | `paid` |\n| `application.deed_issued` | Deed executed | `deed` |\n| `application.lapsed` | Unpaid application auto-expires 14 days after `sent_at` | `expired` |\n| `application.withdrawn` | Withdrawn by staff or tenant | `withdrawn` |\n| `application.reinstated` | A lapsed or tenant-declined application is paid late | `paid`, arrived from `expired` or `withdrawn` |\n| `application.declined` | Criteria decline | **No.** Needs the `declined` status |\n| `reference.completed` | Reference concludes | **No.** Needs the referencing integration |\n\n**`application.reinstated` is emitted instead of `application.paid`**, not in\naddition. Deliveries are unique per endpoint, application and event type, which\ngives at-most-once. Saying nothing would leave a partner who heard\n`application.lapsed` with a permanently wrong record; resending\n`application.paid` would be double counted by anyone treating it as a\nfirst-payment signal, and would be suppressed by the index anyway. A distinct\nevent solves both.\n\nBoth routes into it, a lapsed application paid late and a **tenant-declined**\nwithdrawal paid late, are the same branch of `apply_stripe_payment`\n(20260705115059:66),\nso they behave identically.\n\nA **staff**-withdrawn application paid late emits **nothing at all**, because\nthat branch never changes status. The partner is never told the money arrived.\nwith an event, since the application was not reinstated and real money is sitting\non a withdrawn row awaiting a refund.\n\nStatuses use the partner vocabulary of section 15, never internal values.\n\n**Naming note.** The event for the `expired` status is deliberately called\n`application.lapsed`, not `application.expired`, because the codebase uses\n\"expiry\" for two unrelated things and a partner-facing name must not inherit the\nambiguity:\n\n- `status = 'expired'` means an **unpaid application** lapsed 14 days after\n  `sent_at` (20260705115059:1-2).\n- `expiry_date` is the **guarantee's** expiry, a generated column equal to\n  tenancy start plus 12 months minus a day\n  (core_schema.sql:132).\n\nThese are months apart and mean opposite things commercially. If a guarantee\nexpiry event is ever wanted, it is a separate event and must not reuse this name."
  },
  {
    "id": "13-6-status-is-not-monotonic",
    "title": "Status is not monotonic",
    "body": "An application can move **backwards** out of a terminal-looking state. A later\npayment reinstates both an expired application and a tenant-declined withdrawal\nto `paid`, described in the migration header as \"late money wins\"\n(20260705115059:3-5).\nA staff withdrawal does not reinstate.\n\nSo `application.lapsed` followed by `application.paid` for the same application\nis **normal and correct**, not an error or a duplicate.\n\nPartners must be told this explicitly, because the natural implementation is to\ntreat a lapse as terminal and stop listening. The webhook documentation should\nstate that consumers must:\n\n- Handle any event arriving after a lapse or withdrawal.\n- Treat `status` in the payload as authoritative, not the event name.\n- Order by the event timestamp, not arrival order, since retries mean a later\n  event can arrive before an earlier one."
  },
  {
    "id": "14-error-contract",
    "title": "Error contract",
    "body": "| Status | Code | Meaning |\n| ------ | ---- | ------- |\n| 400 | `malformed_request` | Not valid JSON, or missing idempotency key |\n| 401 | `unauthorized` | Any auth failure, always identical (section 4.4) |\n| 403 | `insufficient_scope` | Key lacks the scope |\n| 403 | `partner_inactive` | Partner not `active` |\n| 404 | `not_found` | Unknown, or belongs to another partner. Indistinguishable by design |\n| 404 | `unsupported_version` | The path carries no API version, or one that is not supported |\n| 409 | `idempotency_key_reused` | Same key, different body |\n| 409 | `request_in_progress` | Same key, still processing |\n| 422 | `validation_failed` | Field errors (section 9.3) |\n| 429 | `rate_limited` | With `Retry-After` |\n| 500 | `internal_error` | With an opaque `request_id`, no internals |\n| 501 | `not_implemented` | The partner's `referencing_mode` is not built. See below |\n| 503 | `service_unavailable` | Dependency down, retryable |\n\nEvery response carries `X-Request-Id`, logged alongside the real reason, so\nsupport can diagnose without the API disclosing anything.\n\n`404` for another partner's resource, rather than `403`, is deliberate: `403`\nconfirms the resource exists.\n\n**`501` is how an unbuilt mode fails, and it is deliberate.** A partner on\n`pre_referenced_screened` or `opndoor_referenced` gets a flat refusal rather than\nbeing quietly treated as `pre_referenced_open`. Accepting them would mean\napproving every applicant with no criteria applied, which looks exactly like\nworking software and would surface as a commercial problem long after the fact.\nThe message does not name the mode, since that is internal vocabulary.\n\n---"
  }
];
